version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=sqlite:///db.sqlite3
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=medvault
      - POSTGRES_USER=medvault
      - POSTGRES_PASSWORD=medvault123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
